version: "0.0.1"
services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_USER}
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
       - dbvol:/data/postgres-tuto
    networks:
      - postgres  

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment: 
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    volumes:
            - ./:/app/
            - dbvol:/app/node_modules
    depends_on:
      - postgres
    networks:
      - postgres

volumes:
    dbvol: {}

networks:
  postgres:
    name: custom_frontend
    driver: bridge
    