version: "0.0.1"
services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
       - dbtuto:/data/postgres-tuto
    links:
      - app
    networks:
      - postgres  

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment: 
      PORT: ${PORT}
    networks:
      - postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres  

volumes:
    dbtuto:
      external: true

networks:
  postgres:
    driver: bridge